eureka:
  client:
    service-url:
      #defaultZone: http://eureka-microserv:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
      #defaultZone: https://microserv-v2.onrender.com/eureka
    registerWithEureka: true
    fetchRegistry: true


server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-route
          uri: ${USER_MICROSERV_URL:lb://user-microserv}
          predicates:
            - Path=/users/**


        - id: product-route
          uri: ${PRODUCT_MICROSERV_URL:lb://product-microserv}
          predicates:
            - Path=/product/**
